---
title: "Historical"
format: html
---

```{r}
Data <- read.csv("data/2018/Sterility_2018.csv", check.names=FALSE)
Data <- read.csv("data/2019/Sterility_2019.csv", check.names=FALSE)
Data <- read.csv("data/2020/Sterility_2020.csv", check.names=FALSE)
Data <- read.csv("data/2021/Sterility_2021.csv", check.names=FALSE)
Data <- read.csv("data/2022/Sterility_2022.csv", check.names=FALSE)
Data <- read.csv("data/2023/Sterility_2023.csv", check.names=FALSE)
Data <- read.csv("data/2024/Sterility_2024.csv", check.names=FALSE)
Data <- read.csv("data/2025/Sterility_2025.csv", check.names=FALSE)
```
```{r}
colnames(Data)
```

# StartHere

```{r}
Value <- "data/2024/Sterility_2024.csv"
Data <- read.csv(Value, check.names=FALSE)
```

```{r}
colnames(Data)
str(Data)
#Data$Type <- gsub("Tube Inoculation Date: ", "", Data$Type)
Data$Date <- gsub("/", "-", Data$Date)
Data$Date <- gsub(" ", "-", Data$Date)
Data$Date <- gsub("2024-01-03", "01-03-2024", Data$Date)
Data$Date |> unique()
lubridate::mdy(Data$Date)
# Data$Date <- lubridate::mdy(Data$Date) # Validate First
Data$Type |> unique()
Data$Type <- gsub(", Tank", "", Data$Type)
Data$Type <- gsub("Sheathe", "Sheath", Data$Type)
Data$Type <- gsub(", ", "_", fixed=TRUE, Data$Type)
Data$Type <- gsub("LB ", "LB", fixed=TRUE, Data$Type)
Data$Type <- gsub("Sheath ", "Sheath_", fixed=TRUE, Data$Type)

Data$Day1 |> unique()
Data$Day1 <- gsub("-", "0", fixed=TRUE, Data$Day1)
Data$Day1 <- gsub("+", "1", fixed=TRUE, Data$Day1)

Data$Day2 |> unique()
Data$Day2 <- gsub("-", "0", fixed=TRUE, Data$Day2)
Data$Day2 <- gsub("+", "1", fixed=TRUE, Data$Day2)

Data$Day3 |> unique()
Data$Day3 <- gsub("-", "0", fixed=TRUE, Data$Day3)
Data$Day3 <- gsub("+", "1", fixed=TRUE, Data$Day3)
```

```{r}
write.csv(Data, Value, row.names=FALSE)
```

